DROP DATABASE IF EXISTS `mechshop`;

CREATE DATABASE mechshop;
USE mechshop;

CREATE TABLE products (
	`slug` VARCHAR(100) PRIMARY KEY,
	`displayname` TEXT NOT NULL, 
	`price` INT NOT NULL, 
	`size` INT NOT NULL, 
	`description` TEXT,
	`usb` TEXT, 
	`bluetooth` BOOLEAN DEFAULT FALSE,
	`rf` BOOLEAN DEFAULT FALSE,
	`backlight` TEXT,
	`mediakeys` BOOLEAN DEFAULT FALSE
);

CREATE TABLE orders (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
	`email` VARCHAR(320) NOT NULL,
	`postcode` INT NOT NULL,
	`city` TEXT NOT NULL,
	`address` TEXT NOT NULL,
	`fullname` TEXT NOT NULL,
	`phone` TEXT NOT NULL,
	`date` DATE NOT NULL
);

CREATE TABLE orderitems (
	`orderid` INT NOT NULL,
	`productid` VARCHAR(100) NOT NULL, 
	`amount` INT NOT NULL,
	FOREIGN KEY (`orderid`) REFERENCES orders(`id`),
	FOREIGN KEY (`productid`) REFERENCES products(`slug`)
);

INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-mini-v2-rgb', 'Ducky One 2 Mini v2 RGB', '29900', 60, 'Featuring PBT double shot seamless keycaps with side laser engraving technique.  Smaller size, but no functions sacrificed. Supports Ducky Macro V2.0 and Mouse control function. The new bezel design shares a similar sleek frame as it�s predecessor, but the One 2 Mini incorporates dual colors on the bezel to match all varieties of keycap  colorways.\n\nTo stand out in the crowd we chose to use PBT seamless double-shot keycaps. It is designed and engineered in a way to provide the user with the best durability and typing experience. Varieties of colorways available.\n\nThe One 2 can be adjusted into three placement angles, optimizing typing comfortability and legend visibility.\n\nDetachable USB Type-C cable provides convenience to users. We use USB HID with the highest frequency of 1000Hz polling rate, meaning the keyboard is sending its input signal(s) to your PC 1000 times per second. This feature minimizes the delay of when the keys are being pressed and signal received by the computer.\n\nEvery Ducky One 2 Mini comes with 10 additional PBT Double-Shot Colorful keycaps (Random color)', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-mini-v2-white-rgb', 'Ducky One 2 Mini v2 White RGB', '29900', 60, 'No description', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-mecha-mini-v2', 'Ducky Mecha Mini v2', '35940', 60, 'The Ducky One 2 Mini Mecha is everything you love about the classic One 2 Mini wrapped in one of the most beautifully balanced frames ever used in a keyboard.  The Mecha''s ground-breaking cast aluminum frame offers stunning aesthetics with curves and features that bulky CNC machined Aluminum frames can only dream of. The weight of the frame is substantial but also balanced and not just heavy for the sake of being heavy.  You have to feel it to believe it.\n\nThe Mecha comes equipped with PBT double shot seamless keycaps with side laser engraving. It has a smaller size, but no functions have been sacrificed. Supports Ducky Macro V2.0 and Mouse control function.\n\nTo stand out in the crowd we chose to use PBT seamless double-shot keycaps. It is designed and engineered in a way to provide the user with the best durability and typing experience. Varieties of colorways available.\n\nDetachable USB Type-C cable provides convenience to users. The Mecha uses USB HID with the highest frequency of 1000Hz polling rate, meaning the keyboard is sending its input signal(s) to your PC 1000 times per second. This feature minimizes the delay of when the keys are being pressed and signal received by the computer.\n\nEvery Ducky One 2 Mini Mecha comes with 10 additional PBT Double-Shot Colorful keycaps (Random color)', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-sf-rgb', 'Ducky One 2 SF RGB', '32920', 65, 'No description', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-rgb-tkl', 'Ducky One 2 RGB TKL', '37750', 80, 'No description', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-sf-rgb-pure-white', 'Ducky One 2 SF RGB Pure White', '32920', 65, 'No description', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-x-mk-mecha-frozen-llama', 'Ducky x MK Mecha Frozen Llama', '38960', 60, 'Bringing back the popular Frozen Llama colorway, exclusively sold through MK, this keyboard blends the best of everything � the visual aesthetic of our sold-out, limited-edition Frozen Llama keyboard; the heart of a Ducky One 2 Mini RGB; and the solid build of a Mecha case � now all in one! \n\n\nThe Mecha''s ground-breaking cast aluminum frame offers stunning aesthetics with curves and features that bulky CNC machined Aluminum frames can only dream of. The result is substantial weight, but in a carefully balanced way � not just heavy for the sake of being heavy. You have to feel it to believe it.\n\n\n\nThe PCB has been updated and improved, and two additional LED lights have been added to the spacebar. The DIP switch function has been newly optimized and a new keycode switch function added. The firmware has also been rewritten to offer a more stable typing experience.\n\n\n\n\n\nAs a 60% layout, the footprint on your desk is a smaller size than a traditional keyboard, yet the Mini still provides all of the controls and functions you�ve come to know and love from Ducky. It supports Ducky Macro V2.0 and Mouse control function, and comes in a variety of top-of-the-line Cherry MX switch options.\n\n\n\nThe detachable USB Type-C cable provides convenience to users. The Mecha uses USB HID with the highest frequency of 1000Hz polling rate �meaning the keyboard is sending its input signal(s) to your PC 1000 times per second. This feature minimizes any delay between the keys being pressed and the signals being received by your computer. \n\n\n\nThe Ducky x MK Frozen Llama Mecha Mini RGB will be manufactured in limited runs, with each round numbered on the case. Get yours while they last � these will go quickly! \n\n\n\nStrictly limited to one per customer.', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-x-varmilo-miya-pro-sakura', 'Ducky x Varmilo MIYA Pro Sakura', '35940', 65, 'No description', 'USB-C', False, False, 'Pink', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-skyline', 'Ducky One 2 Skyline', '29900', 100, 'No description', 'USB-C', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-rgb', 'Ducky One 2 RGB', '38960', 100, 'No description', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-shine-7-blackout', 'Ducky Shine 7 Blackout', '48020', 100, 'The MK Exclusive Initial Release Shine 7 Blackout features a uniquely black zinc alloy top frame.  While black may seem to be the simplest route, the nature of zinc alloy makes achieving a truly beautiful black color quite challenging.  But as we''ve learned... if anyone in the keyboard industry is up for a challenge, it''s Ducky.  Through carefully treated brushed finishing and anodizing, Ducky has added another masterpiece to their collection with the Shine 7 Blackout.  This one belongs in your collection.', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('vortex-race-3', 'Vortex Race 3', '41980', 75, 'Vortex''s newest 75% keyboard, the 83-key Race 3! Do you need dedicated arrow keys that your 60% doesn''t provide, but don''t want the size of a TKL? A 75% may be just for you! Most of the keys are in the "normal" spot, so there''s nearly no learning curve for this keyboard. \n\nThe Race 3 features a silver anodized CNC case and cone feet. It also has DSA keycaps with dye-sub legends in a vintage grey colorway with 19 extra RGBY and MAC keycaps. \n\n3 programmable layers on top of the default layer. Assembled in Taiwan. \nKey switch damage resulting from the removal of keycaps is not covered under warranty.', 'USB 2.0', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-rgb-tkl-pure-white', 'Ducky One 2 RGB TKL Pure White', '37750', 80, 'No description', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-x-varmilo-miya-pro-panda', 'Ducky x Varmilo MIYA Pro Panda', '40770', 65, 'No description', 'USB 2.0', False, False, 'White', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-skyline-tkl', 'Ducky One 2 Skyline TKL', '29900', 80, 'No description', 'USB 2.0', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-shine-7-gunmetal', 'Ducky Shine 7 Gunmetal', '48020', 100, 'Ducky continues to raise the bar with their 7th edition of the most respected backlit keyboard in the industry - the Ducky Shine.  The Shine 7 features a beautiful Zinc Alloy top case that is three times stronger than aluminum,  PBT Double-shot Seamless Keycaps, and German CHERRY MX Key Switches. Keyboard Indicator Lights To alert you when Number lock, Caps lock, Scroll lock & Mouse Functions are on.  3 Level Angle Adjustment for optimal comfort.  A multitude of LED lighting effects including New Equalizer(EQ), Alpha & Tetris lighting modes, Customizable RGB color &speed, and support for Razer Chroma Broadcast. Anti-Ghosting Technology - Under USB, the keyboard can handle any number of simultaneous key presses with the option of N-key Rollover or 6-Key Rollover to support 6-keys at once.  Advanced LED Technology Utilizes 3528 SMD RGB LED for bigger, brighter LED performance.  The Dual-layer PCB provides longer life expectancy & signal stability.', 'USB-C', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('vortex-pok3r-black-case-rgb', 'Vortex POK3R Black Case RGB', '41980', 60, 'No description', 'USB 2.0', False, False, 'RGB', False);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('obinslab-anne-pro-2-white', 'Obinslab Anne Pro 2 White', '28390', 60, 'The firmware has been completely redone with many new functions and features.\n\nThe keyboard supports complete layout re-programming. Love the Anne Pro 2 but miss the flexibility of using a QMK compatible board? No problem! All keys on the keyboard can be remapped to become any key you want through ObinsLab Starter.\n\nTap key functionality enables keys to behave differently when tapped or held. By default, Right shift, Fn1, Fn2, and Right control behave as arrow keys when tapped.\n\nThere are 2 main function keys which can be remapped to your preference. Fn1 and  Fn2 can be mapped to two different function layers that can be customized through ObinsLab Starter. Caps Lock can also be set to act as a �Magic� function key to mirror the behavior of either Fn1 or Fn2. This �Magic� function is particularly useful to make certain functions easily accessible without moving your fingers from the home row. For example, while holding �Magic� function, WASD can behave as arrow keys.\n\nLighting can also be reprogrammed through ObinsLab Starter. RGB backlights are individually addressable and dynamic lighting effects can also be programmed as well. Lighting profiles can be created, saved, and loaded to the keyboard through the software.\n\nUp to 16 key macros can be programmed through the computer software. Saved macros are stored onto the keyboard onboard memory and do not need the use of the computer software to activate.\n\nKeyboard firmware updating is done entirely through ObinsLab Starter, and is much easier than compared to the process for the original Anne Pro. Just plug the USB cable into the board, press update, and the software will automatically download and transfer the firmware update to the board.', 'USB-C', True, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('vortex-pok3r-black-case', 'Vortex POK3R Black Case', '35940', 60, 'No description', 'USB-C', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-x-varmilo-miya-pro-koi', 'Ducky x Varmilo MIYA Pro Koi', '40770', 65, 'No description', 'USB 2.0', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('varmilo-va87m-moonlight', 'Varmilo VA87M Moonlight', '38050', 80, 'No description', 'USB 2.0', False, False, 'White', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-horizon', 'Ducky One 2 Horizon', '29900', 100, 'No description', 'USB-C', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('vortex-race-3-rgb', 'Vortex Race 3 RGB', '48020', 75, 'No description', 'USB 2.0', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('mechanical-keyboards-night-typist', 'Mechanical Keyboards Night Typist', '31410', 100, '\nThe ''Night'' Typing Professional�s Keyboard\nThe MK Night Typist is built for typing professionals who work in both well lit and low light environments. We looked at everything a typing professional cares about in their keyboard and combined it all to create the MK Typist, then we took it one step further and added warm backlighting to create the MK Night Typist.  If you are a typing professional, this is the only keyboard you will ever need.\n\nBacklighting for the Professional\nWhile bright, colorful lights with flashy effects are fun and useful for other keyboards, we took another approach for the Night Typist''s backlighting. We equipped it with industry-first "warm white" lighting making the keys easy to read but not blinding or distracting in low light environments. The beautiful warm white lighting - adjustable with 4 brightness levels - fits perfectly with the Night Typist''s clean, professional aesthetic.\n\nConstruction Quality\nThe weight, feel, and internal component stability of the Night Typist are immediately evident when interacting with the keyboard.  Compare it side-by-side with another keyboard of your choice to truly appreciate the difference.\n\nClean, Professional Aesthetics\nThe classic styling of the Night Typist fits perfectly in a work environment, standing out through clean edges and quality � not flashy lights or branding.\n\nDurable, easy-to-read Keycaps\nThe Night Typist keycaps are constructed using the industry�s most respected material (PBT) and print method (Double Shot) resulting in caps that will remain sharp, readable, and shine-free through years of use.\n\nBest-in-class mechanical switches for a variety of preferences\nCherry MX Blue for high audible and tactile feedback.\nCherry MX Brown Switches for moderate audible and tactile feedback.\nCherry MX Silent Red Switches for minimal audible and linear feedback.\nNew Technology\nThe MK Night Typist features programmable keys, a USB Type C connection, updateable firmware, and 4 dipswitches that allow users to select from 16 different key layouts including QWERTY, Colemak, Norman, Dvorak, Workman, three Minimak varieties, and even Alphabetical.\n\nAffordable\nThe MK Night Typist is the perfect solution for those looking to outfit their office or professional workspace with uniform, high-end backlit input devices without breaking the bank.\n\nBeautiful Artistic Packaging\nThe Night Typist box features stunning artwork making it the perfect gift for the typing professional you know.\n\nWarranty\nAs with all MK brand keyboards, the Night Typist comes with the MK Guarantee which extends the MechanicalKeyboards.com return window from 30 days to 60 days and adds a full year to the keyboard''s standard warranty.\n\n', 'USB-C', False, False, 'White', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-rgb-tkl-pudding-edition', 'Ducky One 2 RGB TKL Pudding Edition', '37750', 80, 'No description', 'USB 2.0', False, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('varmilo-va87m-sakura', 'Varmilo VA87M Sakura', '41980', 80, 'No description', 'USB 2.0', False, False, 'Pink', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-white-case-white-led-tkl', 'Ducky One 2 White Case White LED TKL', '31410', 80, 'No description', 'USB-C', False, False, 'White', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-horizon-tkl', 'Ducky One 2 Horizon TKL', '29900', 80, 'No description', 'USB-C', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('vortex-pok3r-white-case-rgb', 'Vortex POK3R White Case RGB', '41980', 60, 'No description', 'USB 2.0', False, False, 'RGB', False);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('obinslab-anne-pro-2-black', 'Obinslab Anne Pro 2 Black', '28390', 60, 'The firmware has been completely redone with many new functions and features.\n\nThe keyboard supports complete layout re-programming. Love the Anne Pro 2 but miss the flexibility of using a QMK compatible board? No problem! All keys on the keyboard can be remapped to become any key you want through ObinsLab Starter.\n\nTap key functionality enables keys to behave differently when tapped or held. By default, Right shift, Fn1, Fn2, and Right control behave as arrow keys when tapped.\n\nThere are 2 main function keys which can be remapped to your preference. Fn1 and  Fn2 can be mapped to two different function layers that can be customized through ObinsLab Starter. Caps Lock can also be set to act as a �Magic� function key to mirror the behavior of either Fn1 or Fn2. This �Magic� function is particularly useful to make certain functions easily accessible without moving your fingers from the home row. For example, while holding �Magic� function, WASD can behave as arrow keys.\n\nLighting can also be reprogrammed through ObinsLab Starter. RGB backlights are individually addressable and dynamic lighting effects can also be programmed as well. Lighting profiles can be created, saved, and loaded to the keyboard through the software.\n\nUp to 16 key macros can be programmed through the computer software. Saved macros are stored onto the keyboard onboard memory and do not need the use of the computer software to activate.\n\nKeyboard firmware updating is done entirely through ObinsLab Starter, and is much easier than compared to the process for the original Anne Pro. Just plug the USB cable into the board, press update, and the software will automatically download and transfer the firmware update to the board.', 'USB-C', True, False, 'RGB', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('vortex-core', 'Vortex Core', '26880', -1, 'No description', 'USB 2.0', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-mini-skyline-white-led', 'Ducky One 2 Mini Skyline White LED', '26880', 60, 'No description', 'USB 2.0', False, False, 'White', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('varmilo-va87m-cmpyo', 'Varmilo VA87M CMPYO', '38960', 80, 'No description', 'USB 2.0', False, False, 'White', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-x-varmilo-miya-pro-rainbow-rgb', 'Ducky x Varmilo MIYA Pro Rainbow RGB', '40770', 65, 'No description', 'USB 2.0', False, False, 'RGB', False);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-mini-bon-voyage-white-led', 'Ducky One 2 Mini Bon Voyage White LED', '26880', 60, 'No description', 'USB 2.0', False, False, 'White', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('leopold-fc750r-grey/blue-pd', 'Leopold FC750R Grey/Blue PD', '35940', 80, 'No description', 'USB 2.0', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-midnight', 'Ducky One 2 Midnight', '29900', 100, 'No description', 'USB-C', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('leopold-fc660c-black', 'Leopold FC660C Black', '72180', 65, 'No description', 'USB 2.0', False, False, 'n/a', False);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-one-2-mini-good-in-blue-white-led', 'Ducky One 2 Mini Good in Blue White LED', '26880', 60, 'No description', 'USB-C', False, False, 'White', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('vortex-vibe', 'Vortex ViBE', '41980', -1, 'No description', 'USB 2.0', False, False, 'n/a', False);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('vortex-pok3r-white-case', 'Vortex POK3R White Case', '35940', 60, 'No description', 'USB-C', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('varmilo-va87m-beijing-opera', 'Varmilo VA87M Beijing Opera', '44090', 80, 'No description', 'USB 2.0', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('varmilo-va87m-sea-melody', 'Varmilo VA87M Sea Melody', '38050', 80, 'No description', 'USB 2.0', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('leopold-fc750r-two-tone-white-pd', 'Leopold FC750R Two Tone White PD', '35940', 80, 'No description', 'USB 2.0', False, False, 'n/a', True);
INSERT INTO products (slug, displayname, price, size, description, usb, bluetooth, rf, backlight, mediakeys) VALUES ('ducky-mecha-sf-radiant-emerald-edition', 'Ducky Mecha SF Radiant - Emerald Edition', '48020', 65, 'Ducky''s Limited Mecha SF Radiant Series - Emerald Edition.  Featuring an iridescent Aluminum Case and three-tone keycaps.Whatever anyone does or says, we must stay emerald and keep our color.', 'USB-C', False, False, 'RGB', True);
